##Encoding Techniques

1)Label Encoding
2)One-Hot Encoding
3)Ordinal Encoding
4)Target Encoding

In [165]:
#Label Encoding-->It is used to encode categarical col to num because algorthim understand only numbers.
'''
#In  this we encode each  value to number from 0 to n.

                 syntax:from sklearn.preprocessing import LabelEncoder

we  use for target column because it has a less unique values for classification algorithm like yes\no,pass/fail

Example : we have target col like PASS/FAIL

                  1)Take unique character
                              PASS
                              FAIL
                  2)Arange in Alphabet order

                            FAIL
                            PASS
                  3)Assign values

                         FAIL----0
                         PASS----1
                         
'''

In [167]:
#import lib

import pandas as pd
import numpy as np
n_rows=10
data={
    "Result":np.random.choice(["PASS","FAIL"],n_rows)
}

df=pd.DataFrame(data)

In [169]:
df

  Result
0   FAIL
1   PASS
2   FAIL
3   PASS
4   FAIL
5   PASS
6   FAIL
7   FAIL
8   FAIL
9   FAIL

In [171]:
#import LabelEncoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Result"]=le.fit_transform(df["Result"])
df

   Result
0       0
1       1
2       0
3       1
4       0
5       1
6       0
7       0
8       0
9       0

In [ ]:
#2 -One hot encoder

'''   
--->It is encoding technique which create separate columns to unique col
'''

In [174]:
#import  OneHotEncoder
n_rows=10
data={
    "Result":np.random.choice(["GOOD","BAD","AVERAGE"],n_rows)
}

d=pd.DataFrame(data)

from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(sparse_output=False)

values=ohe.fit_transform(d)
col=ohe.get_feature_names_out()

d[col]=values

In [176]:
d

    Result  Result_AVERAGE  Result_BAD  Result_GOOD
0  AVERAGE             1.0         0.0          0.0
1      BAD             0.0         1.0          0.0
2     GOOD             0.0         0.0          1.0
3     GOOD             0.0         0.0          1.0
4  AVERAGE             1.0         0.0          0.0
5      BAD             0.0         1.0          0.0
6  AVERAGE             1.0         0.0          0.0
7  AVERAGE             1.0         0.0          0.0
8      BAD             0.0         1.0          0.0
9  AVERAGE             1.0         0.0          0.0

In [178]:
#ordinalEncoder
#It is used when output is in meaning full arder like poor,avg,good   and  small/large/extra large
n_row=10
data={
    "Size":np.random.choice(["SMALL","MEDIAM","LARGE","EXTRA LARGE"],n_row),
    "Result":np.random.choice(["BAD","AVG","GOOD"],n_row)
}
f=pd.DataFrame(data)

from sklearn.preprocessing import OrdinalEncoder

oe=OrdinalEncoder(categories=[
        ["SMALL", "MEDIAM", "LARGE", "EXTRA LARGE"],
        ["BAD", "AVG", "GOOD"]])
df[["Size","Result"]]=oe.fit_transform(f[["Size","Result"]])

In [180]:
f

     Size Result
0   SMALL    AVG
1  MEDIAM    AVG
2   SMALL    BAD
3  MEDIAM    AVG
4   LARGE    BAD
5   LARGE    AVG
6  MEDIAM    AVG
7   LARGE    BAD
8  MEDIAM   GOOD
9  MEDIAM   GOOD

In [182]:
df

   Result  Size
0     1.0   0.0
1     1.0   1.0
2     0.0   0.0
3     1.0   1.0
4     0.0   2.0
5     1.0   2.0
6     1.0   1.0
7     0.0   2.0
8     2.0   1.0
9     2.0   1.0

In [ ]:
#4 Target encoder

'''
Target Encoding

Target Encoding is a technique used to convert categorical variables into numerical values by replacing each category 
with the mean (or probability) of the target variable for that category.


TargetEncoder is not available in sklearn.preprocessing.


--->Then we install using below command:      pip install category_encoders


--->Import using

            from category_encoders import TargetEncoder

        

'''

In [33]:
import pandas as pd
import numpy as np
n_row=10
data={
    "state":np.random.choice(["Delhi","Goa","karanataka"],n_row),
    "Purchased":np.random.randint(0,2,n_row)
}

df=pd.DataFrame(data)
df

        state  Purchased
0         Goa          0
1       Delhi          1
2       Delhi          0
3  karanataka          1
4       Delhi          1
5       Delhi          0
6         Goa          1
7         Goa          0
8  karanataka          1
9       Delhi          1

In [57]:
from category_encoders import TargetEncoder
# x=df[["state"]].copy()
x=df[["state"]]
y=df["Purchased"]
te=TargetEncoder()
x["state"]=te.fit_transform(x,y)
x

C:\Users\akhil\AppData\Local\Temp\ipykernel_46604\4020649476.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["state"]=te.fit_transform(x,y)

      state
0  0.558809
1  0.600000
2  0.600000
3  0.656740
4  0.600000
5  0.600000
6  0.558809
7  0.558809
8  0.656740
9  0.600000