In [ ]:
#Logestic Regression
# How to select algarith?
# In target column values are continous then regression algorithm If target column values are categiricl then we use  classifcation algoritm

In [3]:
from sklearn.linear_model import LogisticRegression

In [4]:
model=LogisticRegression()

'''
penalty{‘l1’, ‘l2’, ‘elasticnet’, None}, default=’l2’
Specify the norm of the penalty:

None: no penalty is added;

'l2': add an L2 penalty term and it is the default choice;

'l1': add an L1 penalty term;

'elasticnet': both L1 and L2 penalty terms are added.

2)solver-->It is optimized teqhnique

Used when solver == ‘sag’, ‘saga’ or ‘liblinear’ to shuffle the data. See Glossary for details.

solver{‘lbfgs’, ‘liblinear’, ‘newton-cg’, ‘newton-cholesky’, ‘sag’, ‘saga’}, default=’lbfgs’
Algorithm to use in the optimization problem. Default is ‘lbfgs’. To choose a solver, you might want to consider the following aspects:

3)max_iter
max_iterint, default=100(It accepts only integer)
Maximum number of iterations taken for the solvers to converge.

4)class_weight
#how we conform it is inbalance ?
If target col has 
-----How to handle inbalace data ?
-------->we can balance 
                1)class_weight="balanced" ,default=None
                2)Re-sampling




class_weightdict or ‘balanced’, default=None
Weights associated with classes in the form {class_label: weight}. If not given, all classes are supposed to have weight one.

The “balanced” mode uses the values of y to automatically adjust weights inversely proportional to class frequencies in the input data as n_samples / (n_classes * np.bincount(y)).

Note that these weights will be multiplied with sample_weight (passed through the fit method) if sample_weight is specified.

'''
print()

In [48]:
#sag,saga use when we have more feature
# Loan aprovel dataset and loan data
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler
df=pd.read_csv("loan_approval_dataset.csv")
df.head()

,Age,Salary,Credit_Score,Loan_Amount,Loan_Term,Employment_Status,Residence_Type,Previous_Default,Loan_Approved
0,56,136748,584,38209,36 months,Employed,Owned,Yes,Yes
1,46,25287,815,27424,24 months,Self-Employed,Rented,No,Yes
2,32,146593,398,42396,12 months,Unemployed,Rented,Yes,Yes
3,60,54387,696,11370,24 months,Unemployed,Owned,No,No
4,25,28512,788,14528,12 months,Employed,Owned,No,No

In [50]:
x=df.drop(columns="Loan_Approved")
y=df.Loan_Approved

In [52]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=42,train_size=0.8)

In [54]:
x.corr(numeric_only=True)

                   Age    Salary  Credit_Score  Loan_Amount
Age           1.000000  0.060125     -0.018835    -0.000500
Salary        0.060125  1.000000     -0.011185    -0.000635
Credit_Score -0.018835 -0.011185      1.000000     0.008741
Loan_Amount  -0.000500 -0.000635      0.008741     1.000000

In [56]:
num_cols=x.select_dtypes(include="number").columns
obj_col=x.select_dtypes(include="object").columns

In [58]:
encoder=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
scaling=MinMaxScaler()
model=LogisticRegression()

In [60]:
#model.fit(xtrain,ytrain)#ValueError: could not convert string to float: '24 months'

In [62]:
# update xtrain 
xtrain[num_cols]=scaling.fit_transform(xtrain[num_cols])
# xtrain[obj_col]=encoder.fit_transform(xtrain[obj_col])
encoded_values=encoder.fit_transform(xtrain[obj_col])
encoded_columns=encoder.get_feature_names_out()
xtrain[encoded_columns]=encoded_values
xtrain.drop(columns=obj_col,inplace=True)

In [64]:
xtrain

,Age,Salary,Credit_Score,Loan_Amount,Loan_Term_12 months,Loan_Term_24 months,Loan_Term_36 months,Loan_Term_48 months,Employment_Status_Employed,Employment_Status_Self-Employed,Employment_Status_Unemployed,Residence_Type_Mortgage,Residence_Type_Owned,Residence_Type_Rented,Previous_Default_No,Previous_Default_Yes
29,0.565217,0.503206,0.377737,0.267437,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
535,0.434783,0.517503,0.344891,0.125955,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
695,0.586957,0.227507,0.843066,0.766342,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
557,0.630435,0.425421,0.928832,0.792145,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
836,0.608696,0.623919,0.372263,0.599124,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,0.739130,0.759429,0.709854,0.592266,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
270,0.173913,0.889773,0.160584,0.388186,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
860,1.000000,0.884776,0.698905,0.078281,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
435,0.173913,0.213857,0.987226,0.906103,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
102,0.217391,0.456538,0.010949,0.143939,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0

In [66]:
#xtest
xtest[num_cols]=scaling.transform(xtest[num_cols])
# xtrain[obj_col]=encoder.fit_transform(xtrain[obj_col])
encoded_values=encoder.transform(xtest[obj_col])
encoded_columns=encoder.get_feature_names_out()
xtest[encoded_columns]=encoded_values
xtest.drop(columns=obj_col,inplace=True)

In [68]:
xtest

,Age,Salary,Credit_Score,Loan_Amount,Loan_Term_12 months,Loan_Term_24 months,Loan_Term_36 months,Loan_Term_48 months,Employment_Status_Employed,Employment_Status_Self-Employed,Employment_Status_Unemployed,Residence_Type_Mortgage,Residence_Type_Owned,Residence_Type_Rented,Previous_Default_No,Previous_Default_Yes
521,0.152174,0.220886,0.521898,0.540280,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
737,0.434783,0.687894,0.020073,0.453711,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
740,0.347826,0.836468,0.760949,0.652294,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
660,0.434783,0.315031,0.950730,0.116550,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
411,0.934783,0.605720,0.693431,0.587172,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,0.782609,0.894307,0.270073,0.867633,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
332,0.347826,0.976689,0.764599,0.938296,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
208,0.478261,0.012071,0.034672,0.038805,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
613,0.086957,0.540937,0.791971,0.830012,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
78,0.478261,0.261280,0.209854,0.217752,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [70]:
model.fit(xtrain,ytrain)

LogisticRegression()

In [72]:
from sklearn.metrics import precision_score,recall_score,f1_score,confusion_matrix,accuracy_score

In [74]:
#train data Evaluation
ytrain_pred=model.predict(xtrain)
confusion_matrix(ytrain,ytrain_pred)

array([[205, 192],
       [170, 233]], dtype=int64)

In [76]:
precision_score(ytrain,ytrain_pred,pos_label='Yes')

0.548235294117647

In [81]:
recall_score(ytrain,ytrain_pred,pos_label='Yes')

0.5781637717121588

Conclusion:

        -Out of all the actual 'yes'.labels(403),57% labels are correctly predicteed as 'Yes'.

        -Out

In [84]:
recall_score(ytrain,ytrain_pred,pos_label='No')

0.5163727959697733

conclusion:
        - -Out of all the actual 'yes'.labels(403),57% labels are correctly predicteed as 'Yes'.

In [87]:
accuracy_score(ytrain,ytrain_pred)

0.5475

-Conclusion
        -out of all samples(800),54.75% samples are correctly predicted

    'Final Conclusion'
            --Model performance  on tarin data is bad ,so model is not learned train data patterns properly

In [90]:
ytest_pred=model.predict(xtest)
accuracy_score(ytest,ytest_pred)

0.495

In [92]:
from sklearn.metrics import classification_report

In [94]:
print(classification_report(ytrain,ytrain_pred))#recal  means  actual
'''
if inbalnce
'''

              precision    recall  f1-score   support

          No       0.55      0.52      0.53       397
         Yes       0.55      0.58      0.56       403

    accuracy                           0.55       800
   macro avg       0.55      0.55      0.55       800
weighted avg       0.55      0.55      0.55       800

'\nif inbalnce\n'

In [96]:
print(classification_report(ytest,ytest_pred))
'''
accuracy is checked when label are balanced  

'''

              precision    recall  f1-score   support

          No       0.47      0.49      0.48        95
         Yes       0.52      0.50      0.51       105

    accuracy                           0.49       200
   macro avg       0.49      0.49      0.49       200
weighted avg       0.50      0.49      0.50       200

'\naccuracy is checked when label are balanced  \n\n'

In [100]:
#To find unique values count
x[obj_col].nunique()#Less unique values

Loan_Term            4
Employment_Status    3
Residence_Type       3
Previous_Default     2
dtype: int64

##Preprocessing Technique

        -Scaling
        -Encoding
why scaling ?
*Feature (numeric)cols values are in different range(scale).So we need use scaling 
    to give equal impoertance for all the feature  cols.

Why encoding ?
-Algorithm  can understand only numbers not strings

Which Scaling and Encoding Techniques we can use for this ?
scaling -'1'.MinMaxScaler ,2)'StandardScaler'

Encoding:---------->#Less unique values
        Loan_Term            4
        Employment_Status    3
        Residence_Type       3
        Previous_Default     2